# Generated by Django 5.0.3 on 2024-04-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter a Book's natural language (e.g. English, Japanese, Chinese, etc.)", max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
    ]
